FROM python:3

EXPOSE 8501

RUN apt-get install -y git

WORKDIR /usr/src/app

RUN git clone https://github.com/Abhiswain97/ML-from-scratch.git \
    && cd ML-from-scratch \
    && cp -r . /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt

CMD [ "streamlit", "run", "app.py"]